#!/bin/bash
while (( "$#"  )) ; do
	EXPECTED="$1"
	FILE="$2"
	
	if [ ${#EXPECTED} -eq 40 ]; then
		RES="$(shasum -a 1 "$FILE" | awk '{print $1}')"
	else
		RES="$(shasum -a 256 "$FILE" | awk '{print $1}')"
	fi

	if [[ "$RES" == "$EXPECTED" ]]; then
		echo -e "$FILE\t✅ ($RES)"
	else
		echo -e "$FILE\t❌ ($RES != $EXPECTED)"
	fi

	shift
	shift
done
